### PR TITLE
Experiment with a job board

### PR DESCRIPTION
**Pull request by matthewmueller**
Hey folks!

I'm planning to try out a sponsored job board on this repository over the next couple weeks. I'm hoping this can bring in some extra cash to fuel further development and improvement of this library.

If you have any questions, thoughts or concerns, please let me know – thanks!

### CODE REVIEW

**Comment by jugglinmike** [comment]
Hi Matt! This comes as a bit of a surprise; I wasn't aware that we were in need of funding. Could you say more about how you'd like to manage the capital (e.g. collection, bookkeeping, payment) and how you think it should be applied (support requests, bug fixing, feature implementation, documentation improvements, etc.)?

**Comment by fb55** [comment]
^ I second this. I liked the idea of having open collective there in case someone wanted to support cheerio's development (and a couple people did for some time), but this seems completely intransparent.

**Comment by matthewmueller** [comment]
Hey guys, thanks for the feedback. Actually this is something I'm trying out with @tj as a way to better fund open source projects. 

You can find some other experimental job boards here:

- https://github.com/matthewmueller/x-ray
- https://github.com/koajs/koa
- https://github.com/apex/apex

Right now no money is being exchanged, it's just a test run. If/once there is actual dollars at work, I'll  be much more clear about everything.

**Comment by matthewmueller** [comment]
Experiment wasn't as effective as open collective, the traffic coming to github readmes is still not substantial even for big open source projects.

**Pull request merged**
