### PR TITLE
Update to css-select@1.1.0

### PR DESCRIPTION
**Pull request by fb55**
This release adds context support, which adds support for CSS4's `:scope` selector and fixes some issues (eg. spilling inside `.find` or the `:has` selector: Given `<a><b><c>` as a document, `$("b").find("a c")`, as well as `b:has(a c)`, won't match any elements anymore).

It's now pretty easy to implement jQuery's positional pseudo-selectors, I've started working on it in the [cheerio-select](https://github.com/cheeriojs/cheerio-select) repo (once again as a wrapper for css-select). @MatthewMueller's old wrapper included several test that I'd like to adopt, the repo seems to be deleted, though.

### CODE REVIEW

**Comment by davidchambers** [comment]
Sounds good.

**Comment by MatthewMueller** [comment]
Sweet! I think I have it locally. I can push it back up if you'd like

**Comment by fb55** [comment]
@MatthewMueller That would be very helpful :)

**Comment by jugglinmike** [comment]
I removed that dependency a while ago (gh-321 / 30b7338d8e53248d75d32df9991a78bd9420d76d) because it wasn't serving any purpose at the time. What you're suggesting here sounds like a great reason to re-implement it, though!

**Comment by MatthewMueller** [comment]
@fb55 looks like it's already up there! just really old haha: https://github.com/MatthewMueller/cheerio-select

**Comment by jugglinmike** [comment]
Superseded by gh-784

**Pull request closed without merging**
