### PR TITLE
Object.assign is not compatible with node v0.12

### PR DESCRIPTION
**Pull request by 5saviahv**
After writing out `lodash` - function `_.assign` was replaced with `Object.assign`, but this is not compatible with node v0.12

### CODE REVIEW

**Comment by 5saviahv** [comment]
Probably not good idea since it reduces code coverage.

**Comment by TrySound** [comment]
@5saviahv Curious, why do you want to support node 0.12?

**Comment by 5saviahv** [comment]
I have no preference, but Cheerios minimum supported version is currently chosen to be 0.12

Simply using `Object.assign` Cheerios minimum version should be raised to 4.0.0 - I have tested cheerio with 4.0.0 and it works but testing with 0.12 fails.

**Comment by fb55** [comment]
I am also starting to be more and more in favor of bumping the minimum version to Node 4. I do think there is value in supporting old Node versions, but there are only so many hoops worth jumping through for it.

**Pull request closed without merging**
