### PR TITLE
cname: cheerio.js.org

### PR DESCRIPTION
**Pull request by davidchambers**
See cheeriojs/cheeriojs.github.io#1

This is the third step of the [process][1].

[1]: https://dns.js.org/

### CODE REVIEW

**Comment by davidchambers** [comment]
How does this look, @matthewmueller?

**Comment by luanmuniz** [comment]
I think it should be `cheeriojs.org`.
The `.js.org` domain doesn't exist. Right?

**Comment by davidchambers** [comment]
@luanmuniz, have a look at [js.org][1]. ;)


[1]: https://js.org/

**Comment by davidchambers** [comment]
js-org/dns.js.org#774

**Pull request merged**
