### PR TITLE
v1.0.0

### LINKED ISSUE #1047: Add 1.0.0-rc.1 to History.md
npm is telling me that cheerio is out of date, I'm using 0.22.0 and it's suggesting 1.0.0-rc.1. I looked at History.md but there's no indication of what changes are already in 1.0.0-rc.1 and what changes can be expected in 1.0.0, so I'm hoping this could be added to the History file so I can see what new features and breaking changes are there and evaluate whether I want to upgrade yet or wait until later.

### PR DESCRIPTION
**Pull request by fb55**
Wanted to open this to track remaining work and get the final 1.0.0 release going.

__Should be resolved:__

- [ ] #1050
- [x] #1101 (potentially switch serialisers?) — PR open as #1164

__Other improvements:__

- [x] Update css-select dep
- [x] (Optional) use prettier for consistent styling?

Closes #1047, #985

@jugglinmike Anything else you can think of? I should have sufficient availability next week, happy to look into this.

### CODE REVIEW

**Comment by jugglinmike** [comment]
This is great! Thanks for taking the lead here.

One thing from [Matt's original issue about 1.0](https://github.com/cheeriojs/cheerio/issues/442) that I liked was a formalization of the API documentation. [I did some work toward this end in the fall of last year](https://github.com/cheeriojs/cheerio/compare/v1.0.0...jugglinmike:docs), but I never submitted it for review because [JSDoc](http://usejsdoc.org/) (the documentation generator I selected) is [missing a feature that is crucial for the Cheerio API](https://github.com/jsdoc3/jsdoc/issues/1469).

While I think it would be nice to have a solid website available with the announcement of version 1.0, that is far less important than the technical improvements that we want to publish. I'm really pleased that you're taking initiative on this, and I don't want to get in the way. I'm thinking that there is still value in the consistent use of JSDoc over our current solution (where usage information is split between the source code and the overlong `README.md` file) even *without* documentation generation.

If you agree, then I can rebase those changes and remove the build process.

What do you think?

**Comment by fb55** [comment]
Opened PRs for all the changes I wanted to make. Once these are merged we might want to write an accompanying post somewhere (eg. Medium) basically outlining what changed and do a big release :D

**Comment by fb55** [comment]
@jugglinmike Adding jsdoc is still super valuable, and not something we should skip just because we can't model one relationship. We could also use something like https://github.com/bradtaylorsf/markdown-magic-jsdoc as a very simple way to generate markdown from jsdoc comments.

**Comment by jugglinmike** [comment]
One thing I would like to avoid is checking generated assets into the main development branch. That practice causes confusion for new contributors and also adds noise to the commit history.

But your point about the value of the change and the relative unimportance of the issue is well-taken. I think this is a case where I've gotten too hung up on a small detail. Thanks for making that more clear!

I've rebased that documentation branch and submitted it at gh-1165.

Looking forward to writing that blog post :)

**Comment by fb55** [comment]
> One thing I would like to avoid is checking generated assets into the main development branch. That practice causes confusion for new contributors and also adds noise to the commit history.

We should figure out a place to host the documentation then. Having them in the repo would make it easy, as Github pages would just pick them up (and we could link to it). We could even add a precommit hook that automatically generates docs whenever you commit.

One alternative would be something like Netlify, but that has the disadvantage that we would need to add all the build config to the repo & move the website off Github pages.

> Looking forward to writing that blog post :)

You are definitely the one deserving most of the credit here, happy to proof-read drafts or help in any other way!

**Comment by jugglinmike** [comment]
> We should figure out a way to automate generation of docs then. Having them in the main branch would make it easy, as Github pages would just pick them up (and we could link to it). We could even add a precommit hook that automatically generates docs whenever you commit.

There are a couple downsides to using githooks to synchronize redundant documentation files on the `master` branch:

- Increased noise (either via extra "publication" commits or squashed into the code changes themselves)
- Tight coupling between the state of `master` and the state of the website (if `master` has unreleased features, we won't be able to re-publish the docs until we release a new version of the library)

How about publishing docs to a dedicated branch instead? We can push to that branch at any moment, using whatever branch (`master` or some hotfix) that we please.

**Comment by fb55** [comment]
> How about publishing docs to a dedicated branch instead? We can push to that branch at any moment, using whatever branch (master or some hotfix) that we please.

I like that approach, happy to go forward with it!

Sorry for taking a bit :/

**Comment by gajus** [comment]
> Sorry for taking a bit :/

Is the this PR safe to use other than #1050?

**Comment by fb55** [comment]
Merging this to master to push us to get this out eventually. I've created a project that allows us to track progress.

**Comment by jugglinmike** [comment]
Glad to see some movement here, but I think the context of this branch make
GitHub's "Squash and Merge" feature undesirable. I'd like to propose landing
this work with a dedicated merge commit, so I've opened gh-1231 to make that
possible.

Separately: I agree that we should get moving on this, but I'd rather not merge
the branch until it is ready so that `master` remains in a consistent state.

**Pull request merged**
