### PR TITLE
some cases htmlparser2 cant be used for html rendering

### PR DESCRIPTION
**Pull request by 5saviahv**
small fix that allows using htmlparser2 for html rendering, when html string was provided.

### CODE REVIEW

**Comment by bodinsamuel** [comment]
hey @fb55 can we take a look at this please? ☺️ 
related to #1627

**Comment by fb55** [comment]
@bodinsamuel This was also fixed in #1816, and I want to move forward with that PR. I am still waiting a few more days for people to review it, but unless someone brings up any issues, I should be able to issue a new release some time next week.

**Comment by bodinsamuel** [comment]
oh, amazing news and congrats on jumping on the TS wagon 💪🏻 
Can't wait for the update then 🙏🏻

**Comment by fb55** [comment]
Closing this as it has been fixed in #1816. Thanks a lot @5saviahv!

**Pull request closed without merging**
