### PR TITLE
Fix unexpected behavior while querying child

### PR DESCRIPTION
**Pull request by Delgan**
I followed [the solution of fb55](https://github.com/cheeriojs/cheerio/issues/780#issuecomment-166870067) and I added a unit test to ensure that #742 and #780 was correctly fixed.

### CODE REVIEW

**Comment by jugglinmike** [comment]
This looks good to me. I'm not so hot on using `__proto__`, but there's precedence in the project for it, so I'll leave that discussion for another time.

@fb55 Did you author commit 4779762?

**Comment by fb55** [comment]
@jugglinmike No, I did not. It follows a suggestion I made, @Delgan probably wanted to give credit (which I appreciate!). A mention in the commit message would be better IMHO, but I don't care enough about it to force a change.

LGTM otherwise!

**Comment by jackwilsdon** [comment]
+1 on this, having the same issue.

**Comment by adelgado** [comment]
This indeed fixes the issue, thanks :-)

I've seen elsewhere in the repo that releases are request-based, @fb55 is there anything missing for this PR to it be merged and a version containing the fix to be released? Thanks

**Pull request merged**
