### PR TITLE
package.json: Add a "bench" alias script

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by fb55** [comment]
I'm not a super big fan of having aliases in the `package.json`. Should we just rename the original script?

**Comment by XhmikosR** [comment]
Your call, but alias help because they work in more cases. Feel free to close the PR, it's just I kept running `npm run bench`. This should allow both cases to work.

**Comment by fb55** [comment]
Decided to merge this, as we don't have insane amounts of scripts at the moment.

**Comment by fb55** [comment]
Thanks @XhmikosR!

**Pull request merged**
