### PR TITLE
Export ./lib/api/attributes to work with Node v18

### PR DESCRIPTION
**Pull request by InfosecEskimo**

### CODE REVIEW

**Comment by InfosecEskimo** [comment]
@fb55 Thoughts?

**Comment by fb55** [comment]
What is the motivation behind this? Not sure when you'd ever need this file in isolation.

**Comment by InfosecEskimo** [comment]
I'm getting these errors

Catch Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/attributes' is not defined by "exports" in /home/xxxxx/Development/rush/API/rushmarket-api/node_modules/cheerio/package.json

{
  "code": "ERR_PACKAGE_PATH_NOT_EXPORTED"
}
EARLY EXCEPTION: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/attributes' is not defined by "exports" in /home/xxxxx/Development/rush/API/rushmarket-api/node_modules/cheerio/package.json
EARLY EXCEPTION: Package subpath './lib/api/attributes' is not defined by "exports" in /home/xxxx/Development/rush/API/rushmarket-api/node_modules/cheerio/package.json

**Comment by fb55** [comment]
Seems like a duplicate of https://github.com/cheeriojs/cheerio/issues/2732?

**Comment by InfosecEskimo** [comment]
I see, thanks

**Pull request closed without merging**
