### PR TITLE
Implement .serializeArray()

### PR DESCRIPTION
**Pull request by jlep**
jQuery compatible .serializeArray() implementation (http://api.jquery.com/serializeArray/) + test cases. Doesn't handle multiple selections yet.

### CODE REVIEW

**Comment by twolfson** [comment]
+1 Is there anything holding up this PR outside of merge conflicts?

**Comment by jugglinmike** [comment]
@twolfson As noted above, the proposed implementation is not yet feature-complete with jQuery. It needs to be updated to function on selections of length greater than 1.

**Comment by twolfson** [comment]
I have started to get this PR back on its feet. I have a working parity of the current iteration and will be looking into addressing your concerns.

**Comment by twolfson** [comment]
The latest commit is https://github.com/underdogio/cheerio/compare/e689fb3?expand=1 for reference.

**Comment by twolfson** [comment]
I have submitted #631 which includes the commits from this PR so when that closes, then this should as well.

**Comment by twolfson** [comment]
This PR should be good to close. It was superceded by #631 which was superceded by #669 which has been landed.

**Pull request closed without merging**
