### PR TITLE
Make type more permissive, allowing browser usage

### PR DESCRIPTION
**Pull request by karlhorky**
Ref: https://github.com/vfile/vfile/blob/f95280cbd0d8d29a3fd49984e91e7c665175bceb/lib/index.js#L13-L17
Ref: https://github.com/cheeriojs/cheerio/issues/1844

### CODE REVIEW

**Comment by fb55** [comment]
Could you add a test case that doesn't use a buffer? Something like https://github.com/cheeriojs/cheerio/blob/95759d64886d2f4f944daef1d8b706e75aa0154b/src/load.spec.ts#L35

**Comment by karlhorky** [comment]
lol I guess this feature doesn't exist in Cheerio (Uint8Array is not accepted), I guess I'll just close this PR?

**Comment by 5saviahv** [comment]
`content` of **Buffer** is later just converted to string (and it is expected to be "utf8"). 

https://github.com/cheeriojs/cheerio/blob/e0c7cbbffa76aa9af6441be10f19431606a1819d/src/parse.ts#L20-L22

you can do the same with **UInt8Array** just use `Buffer.from( content ).toString( 'utf8' )` to convert it to string.

**Comment by fb55** [comment]
Closing this PR as any change seems quite involved. Thanks for proposing this, @karlhorky!

**Pull request closed without merging**
