### PR TITLE
Ensure text nodes expose the DOM level 1 API

### PR DESCRIPTION
**Pull request by fb55**
Rebased version of #588. We can still optimise performance later on, this works for now.

### CODE REVIEW

**Comment by jugglinmike** [comment]
Something seems to be wrong here, since the tests are failing on TravisCI. I'm spent for the evening, so I can't be much more constructive. I'll try to take a look in the coming days.

**Comment by fb55** [comment]
The issue is how options are read. I wanted to look into it tomorrow, hope you're having a great evening!

**Comment by fb55** [comment]
We used to pass an array as the context to `.text` when a function was passed, which broke things as that array didn't have an `options` property. I fixed this by passing a cheerio object instead of the array.

**Comment by jugglinmike** [comment]
Thanks! I've created gh-1166 so we don't forget about the performance issue or how we'd like to resolve it.

**Pull request merged**
