### PR TITLE
Use individual lodash functions

### PR DESCRIPTION
**Pull request by sotojuan**
May help with #862.

I replaced lodash with individual packages for each function. This brought down the size by ~4mb. Not too bad!

### CODE REVIEW

**Comment by redwoodfavorite** [comment]
👍  Another consequence of this change is that lodash no longer pollutes the global namespace.  I am actually using the react testing library 'enzyme' and it's dependency on 'cheerio' is frustrating for that reason (currently overriding underscore)

Would like to see this change merged! :)

**Comment by sotojuan** [comment]
Ping @fb55 @jugglinmike :-)

**Comment by fb55** [comment]
IMHO keeping the `_` variable and creating an object inside each file would be a bit more readable.

**Comment by sotojuan** [comment]
Hm, I can see that. I don't mind doing that—what does @jugglinmike think?

**Comment by sotojuan** [comment]
Sorry for the late PR—been busy. I think I did what you meant, let me know.

**Comment by fb55** [comment]
Awesome, thanks a lot :)

**Comment by ianstormtaylor** [comment]
It seems like this change should be done using the `lodash/bind` syntax that `4.0` supports (which will cause an even greater reduction in size when using `cheerio` with other dependencies) instead of the `lodash.bind` syntax which requires pegging a module for each function.

**Comment by sotojuan** [comment]
@ianstormtaylor if @fb55 agrees I don't mind submitting a PR for that. So it'd just be installing lodash fully again but using `var bind = require('lodash/bind')`? I'll have to test it later! Thanks.

**Comment by ianstormtaylor** [comment]
@sotojuan yup, exactly like that! It should mean that other deps using `lodash` will also share the deps, even if they require the whole module.

**Comment by sotojuan** [comment]
👍  We'll see what the repo owners think and I'll implement as needed.

**Comment by billyjanitsch** [comment]
@sotojuan @ianstormtaylor I implemented the change you suggested in #913.

**Pull request merged**
