### PR TITLE
Test against node v0.12 --> v4.2

### PR DESCRIPTION
**Pull request by JaKXz**

### CODE REVIEW

**Comment by fb55** [comment]
Thanks, definitely a welcome patch :)

This requires a jsdom update as well, even though AFAIK it is only required for benchmarking. It should probably be updated and moved to `optionalDependencies`.

`0.10` and `0.11` (including the `allow_failures` entry) can be removed, and `latest` should be added.

@JaKXz Could you update your patch to include these changes?

**Comment by JaKXz** [comment]
@fb55 done :)

**Comment by fb55** [comment]
Allowing failures for *unstable* is a good idea. Also, it should be
possible to use containers by passing *sudo: false* in the *.travis.yml*.

**Comment by JaKXz** [comment]
@fb55 I think we're good now - would you like me to squash these commits? otherwise have fun and thanks for a great library :)

**Comment by fb55** [comment]
@JaKXz Squashing the commits would be great, thanks a lot already :)

**Comment by JaKXz** [comment]
@fb55 all done :)

**Comment by fb55** [comment]
Awesome, thanks a lot!

**Pull request merged**
