### PR TITLE
Fixing lodash vulnerability

### PR DESCRIPTION
**Pull request by eklem**
What about this being v1.0.0-rc.4 ?

Test result (same as before lodash version bump):
```
  650 passing (1s)
  1 pending
```

### CODE REVIEW

**Comment by fb55** [comment]
Thanks @eklem!

**Comment by fb55** [comment]
I would want to include updates to my modules in the RC (that would be htmlparser2, as well as the new cheerio-select module). I'm wrapping up the last changes, the next RC should land soon after.

**Comment by eklem** [comment]
Any progress on the `htmlparser2`and `cheerio-select`, @fb55 ?

**Comment by fb55** [comment]
https://github.com/cheeriojs/cheerio-select/issues/2 is currently blocking. If this doesn't get resolved in the next two weeks, I will release the package under a different name.

**Pull request merged**
