### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by sthota-fms**
Need to export package.json for react-native project.

[Please view this issue for further details.](https://github.com/cheeriojs/cheerio/issues/2786)

### CODE REVIEW

**Comment by fb55** [comment]
Not sure I understand why one would want to import the `package.json` file. Could you elaborate?

**Comment by sthota-fms** [comment]
When I try to install cheerio, I get this warning in my console.

image

Therefore, it's expecting ./package.json.

**Comment by michaelfaith** [comment]
Weighing in here.  It's generally good practice to include an export for the `package.json` so that tooling can use it.  For instance, and app that wants to dynamically display what versions of open source packages its using for legal reporting, can do that easily by loading the `package.json`s of its dependencies.  This seems like an easy thing to add, with no real downside.

**Comment by fb55** [comment]
@michaelfaith added

**Pull request closed without merging**
