### PR TITLE
fixed require issue

### PR DESCRIPTION
**Pull request by daemonchen**
fixed require issue

### CODE REVIEW

**Comment by daemonchen** [comment]
fixed some dependencies bug

**Comment by fb55** [comment]
Which platform requires this?

**Comment by jugglinmike** [comment]
We'll need more information before we can consider this for inclusion in `master`. Since we haven't heard back in over a month, I'm going to close this. We can re-open if the information comes to light!

**Comment by ItsCosmo** [comment]
I am not the author of this PR, but please consider re-examining the "fixed require issue". I can explain why this fix is helpful. In my webpack configuration, I am using the "resolve" configuration as follows:
```
resolve {
  root: "./src"
  extension: ['', 'js', 'jsx', 'scss']
}
```
This is quite useful because is makes imports/requires simpler in the source code.

With the original line in cheerio/index.js:

`exports.version = require('./package').version`

The package.json file is not found, giving the error:

`Error: Cannot find module './package' from 'index.js'`

I believe that's because the empty extension is causing webpack to look in the "./src" folder for this file. Changing the line to:

`exports.version = require('./package.json').version`

The file is no longer matched to the resolve.extension, and so it loads properly. I have not been able to find a workaround for this issue. In the interest of making the integration of cheerio as seamless and trouble free as possible in a variety of environments and configurations, this change is warranted. After all, require("./package") is just a shorthand for require("./package.json")

**Comment by luanmuniz** [comment]
I think the extension addition can go in. It look like this is causing problems and its a really simple change. I cant see any down-side.

The only problem with this PR is the changes in the `package.json` file. The owner of the PR add a few dependences for no reason.

**Pull request closed without merging**
