### PR TITLE
.html() send context to parse5

### PR DESCRIPTION
**Pull request by 5saviahv**
using proper context when parsing in .html() 

It solves #1083

### CODE REVIEW

**Comment by fb55** [comment]
Great job @5saviahv!

**Comment by bodinsamuel** [comment]
Hello, this seems to break when used in combinaison with _useHtmlParser2
I know htmlParser2 is somewhat hidden so, is it fixable or is it expected/won't fix? ☺️ 

https://runkit.com/embed/kv9cok8uese9

**Comment by 5saviahv** [comment]
hmm, it seems to be my mistake/typo

**Comment by bodinsamuel** [comment]
Thanks @5saviahv 🙏🏻

**Pull request merged**
